### ISSUE TITLE
Question: Hereditary substitution?

### ISSUE THREAD

**Issue by qcfu-bu** [rlepigre/ocaml-bindlib#13]
Is it possible to implement hereditary substitution using this library?

**Comment by rlepigre** [comment]
I am not very familiar with hereditary substitution, so I can't really tell. What the library gives you is a representation of binders equipped with an efficient (capture-free) substitution operation, and a representation of free variables that can be bound to construct binders. So, I don't see any reason why this could not be used to implement hereditary substitution: what you do after having substituted a variable is up to you, so you can for instance do a case analysis on the obtained term and perform whatever reduction you want. However, when you perform a Bindlib substitution, all occurences of the bound variable are substituted straight away. Anyway, if you give it a shot, I'm happy to help and answer any further questions you may have! :)

That said, from what I understand, hereditary substitution is mainly a proof technique for establishing normalisation of typed calculi, so I don't really get why you would want to define that in OCaml (using Bindlib or otherwise). It seems to me that this is most useful when working in a proof assistant like Coq. Am I missing something here?

**Comment by qcfu-bu** [comment]
Thanks for the response. I was looking at paper's written by Adam Gundry and others on unification. They encode terms in spine form in the code they shared. Their literature always mention that this is accomplished by using hereditary substitution. 

```haskell
data Tm = N Head [Elim]
        | L (Bind Nom Tm)
        | ...

data Elim = A Tm | Hd | Tl
```

It's entirely possible that I'm misunderstanding things. I will try some to make better sense of these things.

**Comment by rlepigre** [comment]
OK, I briefly looked at that paper, and they mention that they are using the "Binders Unbound library of Weirich et al.". So the AST you are looking at relies on the locally nameless representation (basically de Bruijn indices for bound variables, and names for free variables). On the other hand, Bindlib is closer to a higher-order abstract syntax representation (i.e., binders are represented as OCaml closures).

**Comment by qcfu-bu** [comment]
I’m going to mark this as resolved. I was able to implement the feature I wanted through careful treatment of weak head normalization and spine forms.
