### ISSUE TITLE
Is Obj.magic neccessary?

### ISSUE THREAD

**Issue by haselwarter** [rlepigre/ocaml-bindlib#3]
Hi,

I noticed that you use the Obj module. I am rather suspicious of importing code that uses Obj into the core of my programming language / proof assistant. Can you motivate this choice?

cheers

**Comment by rlepigre** [comment]
Hi there,

Well, the main reason for using Obj is that we need to store elements of different types in a closure (you may want to manipulate bound variables of different types), and we want the environment to be represented as an array for obvious efficiency reasons (constant time access). Nonetheless, the way indexes are managed guarantees that any given cell of the environment array contains elements of a fixed type. It might be possible to work around this using GADTs, but it would be very hard and the code would certainly be less efficient.

Anyway, if the environment was not managed correctly, values would get mixed up all the time (even on simple examples), and nothing would work. Even if we did not use Obj, that kind of guarantee could probably not be encoded in OCaml's type system (at least not in a tractable way), and it is in a sense even more important...

Cheers,
Rodolphe

**Comment by craff** [comment]
Hi,

At some point, I was maintening a version using map instead of arrays, but I still used Obj.magic. As said Rodolphe, we could use the new extensible Gadt allowing runtime type representation using only an integer, but I think it would change the interface and "subst" would need one more argument (the runtime type representation).

Another alternative, if you use only one type for bound variables, would be to provide bindlib as a functor. 
But a lot of applications use more than one type of bound variables. 

Normally (like for other library, escpacially those using some C code), Bindlib is type safe and if this is not true, this is a bug of Bindlib. So I think the current use of magic is acceptable.

Cheers,
Christophe
