### ISSUE TITLE
mbinder with different mk_free functions

### ISSUE THREAD

**Issue by qcfu-bu** [rlepigre/ocaml-bindlib#34]
When using `mbinder` with an array of variables that have different `mk_free` functions, bindlib will use the `mk_free` of the first variable in the array. This will cause variables later in the array to lose all information attached to their `mk_free` functions.

```ocaml
type ty =
  | TVar of tvar * knd
  | Arrow of tys * ty
  | TLam of knds * (ty, ty) mbinder
  | TApp of ty * tys

and tys = ty array
and tvar = ty var


let tvar s k : ty var = new_var (fun x -> TVar (x, k)) s
```

The `tvar` function here attaches kind `k` during the creation of a free variable. Suppose an array of variables `x1, x2, x3, ...` are created with kinds `k1, k2, k3, ...`. If these variables are used to create `bnd : mbinder`, unbinding `bnd` will generate 3 fresh variables all with `k1`.

For the `mbinder` type, using an array of `mb_mkfree` functions seems to solve the issue.
```ocaml
type ('a,'b) mbinder = {
  mb_names  : string array;   (* Preferred names for the bound variables. *)
  mb_binds  : bool array;     (* Indicates whether the variables occur.   *)
  mb_rank   : int;            (* Number of remaining free variables.      *)
  mb_mkfree : ('a var -> 'a) array;   (* Injection of variables into domain.      *)
  mb_value  : 'a array -> 'b; (* Substitution function.                   *)
}
```

**Comment by rlepigre** [comment]
That proposal sounds reasonable to me. I don't think I ever wanted to use different `mkfree` functions for different variables in an `mbinder`, but I don't see why we should forbid this. In fact, there were cases where I needed something similar, but went with a sequence of `binder` because I wanted partial application to be possible.

Do you have a branch implementing the proposed change somewhere? If not I can have a go at it in the following week.
