### ISSUE TITLE
Complexity of functions in the documentation (requested by F. Blanqui)

### ISSUE THREAD

**Issue by rlepigre** [rlepigre/ocaml-bindlib#5]
We probably want a paragraph somewhere at the beginning discussing global complexity concerns.

**Comment by craff** [comment]
In this case, complexity is a bit hard to describe due to the use of closure. But something better than nothing can certainly be done!
Typically, subst is in constant time as it is just putting a value in an OCaml closure. The price is paid at term construction and term traversal. This means that a lot of things like beta reduction are typically linear in the number of beta step + the size of the resulting term (if the number of free variables in a subterm is bounded by a constant, which is very often the case, otherwise extra factor are needed). Giving a description of the library that would allow to prove this is difficult.

**Comment by craff** [comment]
I though a bit more about this. A cost function should be associated to each binder and we could probably give enough information to compute the complexity (using amortized complexity) for simple function like one step beta reduction. This cost is computed from the complexity of box and apply_box and used for the complexity of subst. This means for each function, we should define an its time complexity and cost which are mutually recursve. We should also assume that the user is constructing a syntactic tree. It the user uses arbitrary function behind binders, no hope to do complexity.  

 I still think this is hard to explain and should be a separated document and not part of the mli file ? What do you think ?

In fact this is a possible research/paper subject. So I close the issue for now on.
